import type {
  activities,
  activitySessions,
  destinationMarkets,
  imageAssets,
  inventoryMeta,
  locations,
  properties,
  roomOffers,
  transfers,
  transportSegments,
  transportServices,
} from "@/db/schema";
import { generatedMarketInventory } from "@/db/seed/market-manifest";
import { syncedImageAssets } from "@/db/seed/image-assets";

type Insert<T extends { $inferInsert: unknown }> = T["$inferInsert"];

export interface InventorySeed {
  meta: Insert<typeof inventoryMeta>[];
  imageAssets: Insert<typeof imageAssets>[];
  locations: Insert<typeof locations>[];
  markets: Insert<typeof destinationMarkets>[];
  transportServices: Insert<typeof transportServices>[];
  transportSegments: Insert<typeof transportSegments>[];
  properties: Insert<typeof properties>[];
  roomOffers: Insert<typeof roomOffers>[];
  activities: Insert<typeof activities>[];
  activitySessions: Insert<typeof activitySessions>[];
  transfers: Insert<typeof transfers>[];
}

const supportedFrom = "2026-08-28";
const supportedUntil = "2027-03-31";
const everyDay = [0, 1, 2, 3, 4, 5, 6];

export const udaipurSeed: InventorySeed = {
  meta: [
    {
      id: "active",
      version: "travel-seed-v2",
      seededAt: "2026-08-27T00:00:00.000Z",
      supportedFrom,
      supportedUntil,
      currency: "INR",
      dataProvenance: "synthetic",
    },
  ],
  imageAssets: [],
  locations: [
    {
      id: "country:in",
      type: "country",
      name: "India",
      countryCode: "IN",
      timezone: "Asia/Kolkata",
      aliases: ["India"],
      tags: [],
    },
    {
      id: "city:delhi",
      type: "city",
      name: "Delhi",
      countryCode: "IN",
      parentId: "country:in",
      timezone: "Asia/Kolkata",
      latitudeE6: 28_613_900,
      longitudeE6: 77_209_000,
      aliases: ["New Delhi", "NCR"],
      tags: ["origin_hub"],
    },
    {
      id: "airport:del",
      type: "airport",
      name: "Indira Gandhi International Airport",
      countryCode: "IN",
      parentId: "city:delhi",
      timezone: "Asia/Kolkata",
      airportCode: "DEL",
      aliases: ["Delhi Airport", "IGI Airport"],
      tags: ["origin_hub"],
    },
    {
      id: "city:udaipur",
      type: "city",
      name: "Udaipur",
      countryCode: "IN",
      parentId: "country:in",
      timezone: "Asia/Kolkata",
      latitudeE6: 24_585_400,
      longitudeE6: 73_712_500,
      aliases: ["City of Lakes"],
      tags: ["heritage", "lakes", "culture", "relaxed", "couples", "origin_hub"],
      imageAssetKey: "market-udaipur",
    },
    {
      id: "airport:udr",
      type: "airport",
      name: "Maharana Pratap Airport",
      countryCode: "IN",
      parentId: "city:udaipur",
      timezone: "Asia/Kolkata",
      airportCode: "UDR",
      aliases: ["Udaipur Airport", "Dabok Airport"],
      tags: ["arrival_hub", "origin_hub"],
    },
    {
      id: "neighborhood:udaipur-old-city",
      type: "neighborhood",
      name: "Old City",
      countryCode: "IN",
      parentId: "city:udaipur",
      timezone: "Asia/Kolkata",
      aliases: ["Udaipur Old Town"],
      tags: ["central", "heritage", "walkable"],
    },
    {
      id: "neighborhood:udaipur-pichola",
      type: "neighborhood",
      name: "Lake Pichola",
      countryCode: "IN",
      parentId: "city:udaipur",
      timezone: "Asia/Kolkata",
      aliases: ["Pichola"],
      tags: ["lake", "views", "quiet"],
    },
    {
      id: "neighborhood:udaipur-fateh-sagar",
      type: "neighborhood",
      name: "Fateh Sagar",
      countryCode: "IN",
      parentId: "city:udaipur",
      timezone: "Asia/Kolkata",
      aliases: ["Fateh Sagar Lake"],
      tags: ["lake", "relaxed", "family"],
    },
  ],
  markets: [{ locationId: "city:udaipur", region: "india", displayOrder: 2 }],
  transportServices: [
    {
      id: "transport:del-udr-morning",
      mode: "flight",
      operator: "IndiGo",
      operatingWeekdays: everyDay,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 6_900,
      currency: "INR",
      priceUnit: "per_traveller",
    },
    {
      id: "transport:del-udr-early",
      mode: "flight",
      operator: "Air India",
      operatingWeekdays: everyDay,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 5_400,
      currency: "INR",
      priceUnit: "per_traveller",
    },
    {
      id: "transport:udr-del-afternoon",
      mode: "flight",
      operator: "IndiGo",
      operatingWeekdays: everyDay,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 7_100,
      currency: "INR",
      priceUnit: "per_traveller",
    },
    {
      id: "transport:udr-del-evening",
      mode: "flight",
      operator: "Air India",
      operatingWeekdays: everyDay,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 6_300,
      currency: "INR",
      priceUnit: "per_traveller",
    },
  ],
  transportSegments: [
    {
      id: "segment:del-udr-morning-0",
      serviceId: "transport:del-udr-morning",
      segmentIndex: 0,
      fromLocationId: "airport:del",
      toLocationId: "airport:udr",
      departureLocalTime: "09:20:00",
      arrivalLocalTime: "10:45:00",
      durationMinutes: 85,
      operatorNumber: "6E 2421",
    },
    {
      id: "segment:del-udr-early-0",
      serviceId: "transport:del-udr-early",
      segmentIndex: 0,
      fromLocationId: "airport:del",
      toLocationId: "airport:udr",
      departureLocalTime: "05:50:00",
      arrivalLocalTime: "07:15:00",
      durationMinutes: 85,
      operatorNumber: "AI 469",
    },
    {
      id: "segment:udr-del-afternoon-0",
      serviceId: "transport:udr-del-afternoon",
      segmentIndex: 0,
      fromLocationId: "airport:udr",
      toLocationId: "airport:del",
      departureLocalTime: "15:10:00",
      arrivalLocalTime: "16:35:00",
      durationMinutes: 85,
      operatorNumber: "6E 2422",
    },
    {
      id: "segment:udr-del-evening-0",
      serviceId: "transport:udr-del-evening",
      segmentIndex: 0,
      fromLocationId: "airport:udr",
      toLocationId: "airport:del",
      departureLocalTime: "19:20:00",
      arrivalLocalTime: "20:45:00",
      durationMinutes: 85,
      operatorNumber: "AI 470",
    },
  ],
  properties: [
    {
      id: "property:udaipur-haveli-courtyard",
      name: "Haveli Courtyard",
      locationId: "neighborhood:udaipur-old-city",
      ratingTenths: 45,
      reviewCount: 1_284,
      amenities: ["wifi", "breakfast", "restaurant"],
      accessibility: ["elevator"],
      tags: ["central", "heritage", "family"],
      imageAssetKey: "stay-haveli-courtyard",
    },
    {
      id: "property:udaipur-pichola-retreat",
      name: "Pichola Retreat",
      locationId: "neighborhood:udaipur-pichola",
      ratingTenths: 47,
      reviewCount: 863,
      amenities: ["wifi", "breakfast", "pool", "restaurant"],
      accessibility: ["elevator", "step_free_entry"],
      tags: ["lake", "quiet", "premium", "senior_friendly"],
      imageAssetKey: "stay-pichola-retreat",
    },
    {
      id: "property:udaipur-fateh-sagar-house",
      name: "Fateh Sagar House",
      locationId: "neighborhood:udaipur-fateh-sagar",
      ratingTenths: 43,
      reviewCount: 524,
      amenities: ["wifi", "breakfast"],
      accessibility: ["step_free_entry"],
      tags: ["value", "relaxed", "family", "senior_friendly"],
      imageAssetKey: "stay-fateh-sagar-house",
    },
    {
      id: "property:udaipur-old-town-rooms",
      name: "Old Town Rooms",
      locationId: "neighborhood:udaipur-old-city",
      ratingTenths: 40,
      reviewCount: 311,
      amenities: ["wifi"],
      accessibility: [],
      tags: ["budget", "central", "stairs"],
      imageAssetKey: "stay-old-town-rooms",
    },
  ],
  roomOffers: [
    {
      id: "room:haveli-deluxe",
      propertyId: "property:udaipur-haveli-courtyard",
      roomLabel: "Deluxe Room",
      maxOccupancy: 2,
      inventoryCount: 8,
      mealPlan: "breakfast",
      refundable: true,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 6_200,
      currency: "INR",
      priceUnit: "per_room_per_night",
    },
    {
      id: "room:haveli-family",
      propertyId: "property:udaipur-haveli-courtyard",
      roomLabel: "Family Room",
      maxOccupancy: 4,
      inventoryCount: 3,
      mealPlan: "breakfast",
      refundable: true,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 9_800,
      currency: "INR",
      priceUnit: "per_room_per_night",
    },
    {
      id: "room:pichola-lake-view",
      propertyId: "property:udaipur-pichola-retreat",
      roomLabel: "Lake View Room",
      maxOccupancy: 2,
      inventoryCount: 6,
      mealPlan: "breakfast",
      refundable: true,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 10_500,
      currency: "INR",
      priceUnit: "per_room_per_night",
    },
    {
      id: "room:pichola-suite",
      propertyId: "property:udaipur-pichola-retreat",
      roomLabel: "Lake Suite",
      maxOccupancy: 3,
      inventoryCount: 2,
      mealPlan: "breakfast",
      refundable: true,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 15_800,
      currency: "INR",
      priceUnit: "per_room_per_night",
    },
    {
      id: "room:fateh-sagar-standard",
      propertyId: "property:udaipur-fateh-sagar-house",
      roomLabel: "Standard Room",
      maxOccupancy: 3,
      inventoryCount: 5,
      mealPlan: "breakfast",
      refundable: true,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 4_800,
      currency: "INR",
      priceUnit: "per_room_per_night",
    },
    {
      id: "room:old-town-basic",
      propertyId: "property:udaipur-old-town-rooms",
      roomLabel: "Basic Double",
      maxOccupancy: 2,
      inventoryCount: 7,
      mealPlan: "none",
      refundable: false,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 2_900,
      currency: "INR",
      priceUnit: "per_room_per_night",
    },
  ],
  activities: [
    {
      id: "activity:udaipur-city-palace",
      name: "City Palace visit",
      locationId: "neighborhood:udaipur-old-city",
      tags: ["heritage", "culture", "architecture"],
      mobility: "medium",
      childFriendly: true,
      seniorFriendly: true,
      imageAssetKey: "activity-city-palace",
    },
    {
      id: "activity:udaipur-pichola-boat",
      name: "Lake Pichola boat ride",
      locationId: "neighborhood:udaipur-pichola",
      tags: ["lake", "relaxed", "sunset"],
      mobility: "low",
      childFriendly: true,
      seniorFriendly: true,
      imageAssetKey: "activity-pichola-boat",
    },
    {
      id: "activity:udaipur-bagore-show",
      name: "Bagore Ki Haveli cultural show",
      locationId: "neighborhood:udaipur-old-city",
      tags: ["culture", "evening", "dance"],
      mobility: "low",
      childFriendly: true,
      seniorFriendly: true,
      imageAssetKey: "activity-bagore-show",
    },
    {
      id: "activity:udaipur-saheliyon-bari",
      name: "Saheliyon Ki Bari gardens",
      locationId: "neighborhood:udaipur-fateh-sagar",
      tags: ["gardens", "relaxed", "heritage"],
      mobility: "low",
      childFriendly: true,
      seniorFriendly: true,
      imageAssetKey: "activity-saheliyon-bari",
    },
    {
      id: "activity:udaipur-monsoon-palace-hike",
      name: "Monsoon Palace hillside walk",
      locationId: "city:udaipur",
      tags: ["views", "outdoors", "sunset"],
      mobility: "high",
      childFriendly: false,
      seniorFriendly: false,
      imageAssetKey: "activity-monsoon-palace",
    },
  ],
  activitySessions: [
    {
      id: "session:city-palace-morning",
      activityId: "activity:udaipur-city-palace",
      operatingWeekdays: everyDay,
      startsAtLocalTime: "09:30:00",
      durationMinutes: 150,
      capacity: 30,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 450,
      currency: "INR",
      priceUnit: "per_participant",
    },
    {
      id: "session:pichola-boat-sunset",
      activityId: "activity:udaipur-pichola-boat",
      operatingWeekdays: everyDay,
      startsAtLocalTime: "17:00:00",
      durationMinutes: 60,
      capacity: 20,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 900,
      currency: "INR",
      priceUnit: "per_participant",
    },
    {
      id: "session:bagore-show-evening",
      activityId: "activity:udaipur-bagore-show",
      operatingWeekdays: everyDay,
      startsAtLocalTime: "19:00:00",
      durationMinutes: 75,
      capacity: 40,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 350,
      currency: "INR",
      priceUnit: "per_participant",
    },
    {
      id: "session:saheliyon-bari-afternoon",
      activityId: "activity:udaipur-saheliyon-bari",
      operatingWeekdays: everyDay,
      startsAtLocalTime: "15:00:00",
      durationMinutes: 90,
      capacity: 30,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 120,
      currency: "INR",
      priceUnit: "per_participant",
    },
    {
      id: "session:monsoon-palace-afternoon",
      activityId: "activity:udaipur-monsoon-palace-hike",
      operatingWeekdays: everyDay,
      startsAtLocalTime: "15:30:00",
      durationMinutes: 180,
      capacity: 15,
      validFrom: supportedFrom,
      validUntil: supportedUntil,
      priceAmount: 700,
      currency: "INR",
      priceUnit: "per_participant",
    },
  ],
  transfers: [
    {
      id: "transfer:udr-old-city",
      fromLocationId: "airport:udr",
      toLocationId: "neighborhood:udaipur-old-city",
      mode: "car",
      durationMinutes: 45,
      capacity: 3,
      priceAmount: 1_200,
      currency: "INR",
      priceUnit: "per_vehicle",
    },
    {
      id: "transfer:old-city-udr",
      fromLocationId: "neighborhood:udaipur-old-city",
      toLocationId: "airport:udr",
      mode: "car",
      durationMinutes: 45,
      capacity: 3,
      priceAmount: 1_200,
      currency: "INR",
      priceUnit: "per_vehicle",
    },
    {
      id: "transfer:udr-pichola",
      fromLocationId: "airport:udr",
      toLocationId: "neighborhood:udaipur-pichola",
      mode: "car",
      durationMinutes: 50,
      capacity: 3,
      priceAmount: 1_350,
      currency: "INR",
      priceUnit: "per_vehicle",
    },
    {
      id: "transfer:pichola-udr",
      fromLocationId: "neighborhood:udaipur-pichola",
      toLocationId: "airport:udr",
      mode: "car",
      durationMinutes: 50,
      capacity: 3,
      priceAmount: 1_350,
      currency: "INR",
      priceUnit: "per_vehicle",
    },
    {
      id: "transfer:old-city-fateh-sagar",
      fromLocationId: "neighborhood:udaipur-old-city",
      toLocationId: "neighborhood:udaipur-fateh-sagar",
      mode: "car",
      durationMinutes: 25,
      capacity: 3,
      priceAmount: 500,
      currency: "INR",
      priceUnit: "per_vehicle",
    },
    {
      id: "transfer:fateh-sagar-old-city",
      fromLocationId: "neighborhood:udaipur-fateh-sagar",
      toLocationId: "neighborhood:udaipur-old-city",
      mode: "car",
      durationMinutes: 25,
      capacity: 3,
      priceAmount: 500,
      currency: "INR",
      priceUnit: "per_vehicle",
    },
  ],
};

export const travelInventorySeed: InventorySeed = {
  meta: udaipurSeed.meta,
  imageAssets: syncedImageAssets,
  locations: [...udaipurSeed.locations, ...generatedMarketInventory.locations],
  markets: [...udaipurSeed.markets, ...generatedMarketInventory.markets],
  transportServices: [
    ...udaipurSeed.transportServices,
    ...generatedMarketInventory.transportServices,
  ],
  transportSegments: [
    ...udaipurSeed.transportSegments,
    ...generatedMarketInventory.transportSegments,
  ],
  properties: [...udaipurSeed.properties, ...generatedMarketInventory.properties],
  roomOffers: [...udaipurSeed.roomOffers, ...generatedMarketInventory.roomOffers],
  activities: [...udaipurSeed.activities, ...generatedMarketInventory.activities],
  activitySessions: [
    ...udaipurSeed.activitySessions,
    ...generatedMarketInventory.activitySessions,
  ],
  transfers: [...udaipurSeed.transfers, ...generatedMarketInventory.transfers],
};
