import { config } from "dotenv";
import { and, asc, eq, isNotNull } from "drizzle-orm";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { createDatabase } from "@/db/client";
import { imageAssets } from "@/db/schema";

config({ path: ".env.local" });
config({ path: ".env" });

const outputPath = resolve("src/db/seed/image-assets.ts");

async function main() {
  const connectionString = process.env.DATABASE_ADMIN_URL;
  if (!connectionString) throw new Error("DATABASE_ADMIN_URL is required");

  const db = createDatabase(connectionString);
  const rows = await db
    .select({
      key: imageAssets.key,
      source: imageAssets.source,
      sourceId: imageAssets.sourceId,
      url: imageAssets.url,
      photographer: imageAssets.photographer,
      photographerUrl: imageAssets.photographerUrl,
      sourceUrl: imageAssets.sourceUrl,
      altText: imageAssets.altText,
      width: imageAssets.width,
      height: imageAssets.height,
    })
    .from(imageAssets)
    .where(and(eq(imageAssets.source, "pexels"), isNotNull(imageAssets.url)))
    .orderBy(asc(imageAssets.key));

  const contents = `import type { InventorySeed } from "@/db/seed/data";\n\n/** Generated by npm run db:sync:images. Do not edit manually. */\nexport const syncedImageAssets: InventorySeed["imageAssets"] = ${JSON.stringify(rows, null, 2)};\n`;
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, contents, "utf8");
  process.stdout.write(`Synced ${rows.length} Pexels image assets to ${outputPath}\n`);
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
