import { createHash } from "node:crypto";
import {
  agentNextActionSchema,
  factBundleSchema,
  planningHypothesisSchema,
  validateAgentNextAction,
  validatePlanningHypothesis,
  type AgentNextAction,
  type ContractViolation,
  type FactBundle,
  type GroundedFact,
  type PlannerBudgetState,
  type PlannerScope,
  type PlanningHypothesis,
} from "@/agent/contracts";
import {
  assembleProposedPlan,
  type PlanAssemblyResult,
  type ProposePlanAction,
} from "@/agent/assembler";
import {
  executeToolPlan,
  type ExecutedToolCall,
  type InventoryToolServices,
} from "@/agent/executor";
import { tripDurationDays, tripNightCount } from "@/domain/dates";
import type { PlannableTripRequest } from "@/domain/model";
import { requirePlannableRequest } from "@/domain/request";
import {
  activityCallFitsRoute,
  requiredRouteCalls,
} from "@/domain/route";
import { createDeterministicPlannerModel } from "@/agent/deterministic-planner";
import type {
  LocationNode,
  ResolvedOffer,
  TripProjection,
  TripValidation,
} from "@/domain/trip";

export type CoordinatorPhase =
  | "hypothesis"
  | "after_evidence_round_1"
  | "after_evidence_round_2"
  | "repair_after_validation"
  | "repair_after_search";

export interface PlannerDecisionInput {
  phase: Exclude<CoordinatorPhase, "hypothesis">;
  request: PlannableTripRequest;
  hypothesis: PlanningHypothesis;
  observations: ExecutedToolCall["observation"][];
  factBundles: FactBundle[];
  budget: PlannerBudgetState;
  validationFeedback?: {
    validation: TripValidation;
    factBundle: FactBundle;
    selectedCandidateIds: string[];
  };
}

export interface SpecifiedDestinationPlannerModel {
  /** When true, route/evidence strategy is generated by code and does not call a model. */
  readonly deterministicStrategy?: boolean;
  createPlanningHypothesis(input: {
    request: PlannableTripRequest;
    catalogScope: {
      locationGraph: LocationNode[];
      marketIds: string[];
      supportedThemes: string[];
    };
  }): Promise<unknown>;
  chooseNextAction(input: PlannerDecisionInput): Promise<unknown>;
}

export interface SpecifiedPlanCoordinatorInput {
  tripId: string;
  request: PlannableTripRequest;
  locationGraph: LocationNode[];
  knownMarketIds: ReadonlySet<string>;
  supportedThemes: ReadonlySet<string>;
  optionalClarificationUsed?: boolean;
  expectedInventoryVersion?: string;
  model: SpecifiedDestinationPlannerModel;
  inventoryServices: InventoryToolServices;
  resolveOffer(offerId: string): Promise<ResolvedOffer>;
}

export interface PlanRunTrace {
  hypothesis: PlanningHypothesis;
  actions: AgentNextAction[];
  executedCalls: ExecutedToolCall[];
  validationAttempts: TripValidation[];
  finalBudget: PlannerBudgetState;
}

export type SpecifiedPlanCoordinatorResult =
  | {
      status: "completed";
      trip: Extract<PlanAssemblyResult, { status: "valid" }>['trip'];
      projection: TripProjection;
      trace: PlanRunTrace;
    }
  | {
      status: "needs_optional_clarification";
      topic: Extract<AgentNextAction, { type: "clarify" }>['topic'];
      trace: PlanRunTrace;
    }
  | {
      status: "cannot_satisfy";
      conflictFactIds: string[];
      suggestedRelaxationIds: string[];
      factBundle?: FactBundle;
      trace: PlanRunTrace;
    }
  | {
      status: "invalid_after_repair";
      trip: Extract<PlanAssemblyResult, { status: "invalid" }>['trip'];
      projection: TripProjection;
      factBundle?: FactBundle;
      trace: PlanRunTrace;
    };

export class PlanCoordinatorError extends Error {
  constructor(
    public readonly code:
      | "INVALID_CONTEXT"
      | "MODEL_FAILURE"
      | "INVALID_MODEL_OUTPUT"
      | "WORKFLOW_VIOLATION",
    message: string,
    public readonly details: {
      phase?: CoordinatorPhase;
      violations?: ContractViolation[];
    } = {},
  ) {
    super(message);
    this.name = "PlanCoordinatorError";
  }
}

function initialBudget(optionalClarificationUsed: boolean): PlannerBudgetState {
  return {
    evidenceRoundsUsed: 0,
    repairRoundsUsed: 0,
    searchCallsUsed: 0,
    optionalClarificationUsed,
    priorCallSignatures: new Set(),
  };
}

function coordinatorScope(
  request: PlannableTripRequest,
  input: SpecifiedPlanCoordinatorInput,
): PlannerScope {
  return {
    tripDurationDays: tripDurationDays(request.startDate, request.endDate),
    tripNights: tripNightCount(request.startDate, request.endDate),
    knownLocationIds: new Set(input.locationGraph.map((node) => node.id)),
    knownMarketIds: input.knownMarketIds,
    knownSelectionIds: new Set(),
    supportedThemes: new Set([
      ...[...input.supportedThemes].map((theme) => theme.toLocaleLowerCase("en")),
      ...(request.preferences.interests ?? []).map((theme) => theme.toLocaleLowerCase("en")),
    ]),
    originId: request.origin,
    requestedDestinationId:
      request.destination.kind === "specified" ? request.destination.locationId : undefined,
    locationGraph: input.locationGraph,
  };
}

async function modelHypothesis(
  model: SpecifiedDestinationPlannerModel,
  request: PlannableTripRequest,
  input: SpecifiedPlanCoordinatorInput,
): Promise<PlanningHypothesis> {
  let output: unknown;
  try {
    output = await model.createPlanningHypothesis({
      request,
      catalogScope: {
        locationGraph: [...input.locationGraph].sort((left, right) =>
          left.id.localeCompare(right.id, "en"),
        ),
        marketIds: [...input.knownMarketIds].sort((left, right) =>
          left.localeCompare(right, "en"),
        ),
        supportedThemes: [...input.supportedThemes].sort((left, right) =>
          left.localeCompare(right, "en"),
        ),
      },
    });
  } catch {
    throw new PlanCoordinatorError("MODEL_FAILURE", "Planner model failed while creating a hypothesis", {
      phase: "hypothesis",
    });
  }
  const parsed = planningHypothesisSchema.safeParse(output);
  if (!parsed.success) {
    throw new PlanCoordinatorError("INVALID_MODEL_OUTPUT", "Planner hypothesis has an invalid shape", {
      phase: "hypothesis",
    });
  }
  return parsed.data;
}

async function modelAction(
  model: SpecifiedDestinationPlannerModel,
  input: PlannerDecisionInput,
): Promise<AgentNextAction> {
  let output: unknown;
  try {
    output = await model.chooseNextAction(input);
  } catch {
    throw new PlanCoordinatorError("MODEL_FAILURE", "Planner model failed while choosing the next action", {
      phase: input.phase,
    });
  }
  const parsed = agentNextActionSchema.safeParse(output);
  if (!parsed.success) {
    throw new PlanCoordinatorError("INVALID_MODEL_OUTPUT", "Planner next action has an invalid shape", {
      phase: input.phase,
    });
  }
  return parsed.data;
}

function factsFromExecutions(executions: ExecutedToolCall[]): FactBundle {
  const facts = new Map<string, GroundedFact>();
  executions.forEach((execution) =>
    execution.observation.candidates.forEach((candidate) =>
      candidate.facts.forEach((candidateFact) => facts.set(candidateFact.id, candidateFact)),
    ),
  );
  const values = [...facts.values()].sort((left, right) => left.id.localeCompare(right.id, "en"));
  const availableDimensions = new Set(values.map((item) => item.dimension));
  const comparisonPriority = [
    "total_price",
    "unit_price",
    "duration",
    "stops",
    "departure",
    "arrival",
    "rating",
    "review_count",
    "location",
    "amenities",
    "meal_plan",
    "refundable",
    "capacity",
    "mobility",
    "themes",
  ];
  const allowedComparisonDimensions = [
    ...comparisonPriority.filter((dimension) => availableDimensions.has(dimension)),
    ...[...availableDimensions]
      .filter((dimension) => !comparisonPriority.includes(dimension))
      .sort((left, right) => left.localeCompare(right, "en")),
  ].slice(0, 12);
  return factBundleSchema.parse({
    facts: values,
    allowedComparisonDimensions,
    allowedFollowUpActions: [],
  });
}

function validationFactId(issueId: string): string {
  return `fact:validation:${createHash("sha256").update(issueId).digest("hex").slice(0, 20)}`;
}

function constraintActionLabel(constraintId: string, request?: PlannableTripRequest): string {
  const category = ["budget", "travel", "stay", "activity", "schedule"].find((name) => constraintId.includes(`:${name}`)) ?? constraintId;
  if (category === "budget") {
    const current = request?.constraints.find((constraint) => constraint.id === constraintId);
    const amount = current?.category === "budget" ? current.value.maxTotal?.amount : undefined;
    if (amount) return `Increase the budget by ₹5,000 (to ₹${(amount + 5_000).toLocaleString("en-IN")})`;
    return "Increase the budget by ₹5,000";
  }
  const labels: Record<string, string> = {
    budget: "Increase the budget",
    travel: "Allow more travel options",
    stay: "Relax stay requirements",
    activity: "Relax activity requirements",
    schedule: "Loosen the daily schedule",
  };
  return labels[category] ?? "Relax this requirement";
}

function validationFactBundle(tripId: string, validation: TripValidation, request?: PlannableTripRequest): FactBundle {
  const actions = new Map<
    string,
    { id: string; label: string; type: "adjust_constraint" | "change_scope" }
  >();
  const facts: GroundedFact[] = validation.issues.map((issue) => {
    issue.constraintIds?.forEach((constraintId) => {
      const id = `action:adjust:${constraintId}`;
      actions.set(id, {
        id,
        label: constraintActionLabel(constraintId, request),
        type: "adjust_constraint",
      });
    });
    if (!issue.constraintIds?.length && issue.severity === "error") {
      const issueCode = issue.code.toLocaleLowerCase("en");
      if (issue.code === "ITINERARY_INCOMPLETE") {
        if (request?.preferences.pace !== "relaxed") {
          actions.set("action:change-scope:pace:relaxed", {
            id: "action:change-scope:pace:relaxed",
            label: "Use a relaxed itinerary pace",
            type: "change_scope",
          });
        } else {
          actions.set("action:change-scope:shorter-trip", {
            id: "action:change-scope:shorter-trip",
            label: "Shorten the trip by one day",
            type: "change_scope",
          });
        }
        actions.set("action:change-scope:destination", {
          id: "action:change-scope:destination",
          label: "Compare destinations with fuller activity coverage",
          type: "change_scope",
        });
      } else {
        const id = `action:change-scope:${issueCode}`;
        const scopeLabels: Record<string, string> = {
          route_gap: "Choose a route with complete coverage",
          schedule_conflict: "Relax the daily schedule",
        };
        actions.set(id, {
          id,
          label: scopeLabels[issueCode] ?? "Choose a compatible trip scope",
          type: "change_scope",
        });
      }
    }
    return {
      id: validationFactId(issue.id),
      subjectType: "trip",
      subjectId: tripId,
      dimension: "validation",
      label: issue.message,
      value: issue.code,
    };
  });
  return factBundleSchema.parse({
    facts,
    allowedComparisonDimensions: ["validation"],
    allowedFollowUpActions: [...actions.values()].sort((left, right) =>
      left.id.localeCompare(right.id, "en"),
    ),
  });
}

function validateAction(
  action: AgentNextAction,
  request: PlannableTripRequest,
  input: SpecifiedPlanCoordinatorInput,
  executions: ExecutedToolCall[],
  factBundles: FactBundle[],
  budget: PlannerBudgetState,
  phase: Exclude<CoordinatorPhase, "hypothesis">,
) {
  const scope = coordinatorScope(request, input);
  const validation = validateAgentNextAction(
    action,
    {
      ...scope,
      observations: executions.map((execution) => execution.observation),
      factBundles,
    },
    budget,
  );
  if (!validation.valid) {
    throw new PlanCoordinatorError(
      "INVALID_MODEL_OUTPUT",
      "Planner action failed deterministic scoped validation",
      { phase, violations: validation.violations },
    );
  }
  if (action.type !== "propose_plan") return;

  const route = {
    originId: request.origin,
    marketId: action.marketId,
    stopIds: action.stopIds,
    nightAllocation: action.nightAllocation,
    tripDurationDays: tripDurationDays(request.startDate, request.endDate),
  };
  const routeViolations: ContractViolation[] = [];

  const requirements = requiredRouteCalls(route);
  action.choices.forEach((choice) => {
    const matchingExecutions = executions.filter((execution) =>
      execution.observation.candidates.some(
        (candidate) => candidate.candidateId === choice.candidateId,
      ),
    );
    const belongsToRoute = matchingExecutions.some((execution) =>
      requirements.some((requirement) => requirement.matches(execution.call)) ||
      (execution.call.tool === "search_activities" &&
        activityCallFitsRoute(route, execution.call, input.locationGraph)),
    );
    if (!belongsToRoute) {
      routeViolations.push({
        code: "INVALID_ROUTE_SCOPE",
        message: `Candidate ${choice.candidateId} does not belong to the proposed route`,
        referenceId: choice.candidateId,
      });
    }
  });

  if (routeViolations.length > 0) {
    throw new PlanCoordinatorError(
      "INVALID_MODEL_OUTPUT",
      "Planner proposal contains candidates outside the declared route",
      { phase, violations: routeViolations },
    );
  }
}

function trace(
  hypothesis: PlanningHypothesis,
  actions: AgentNextAction[],
  executions: ExecutedToolCall[],
  validations: TripValidation[],
  budget: PlannerBudgetState,
): PlanRunTrace {
  return {
    hypothesis,
    actions: [...actions],
    executedCalls: [...executions],
    validationAttempts: [...validations],
    finalBudget: budget,
  };
}

function clarificationResult(
  action: Extract<AgentNextAction, { type: "clarify" }>,
  hypothesis: PlanningHypothesis,
  actions: AgentNextAction[],
  executions: ExecutedToolCall[],
  validations: TripValidation[],
  budget: PlannerBudgetState,
): SpecifiedPlanCoordinatorResult {
  return {
    status: "needs_optional_clarification",
    topic: action.topic,
    trace: trace(hypothesis, actions, executions, validations, {
      ...budget,
      optionalClarificationUsed: true,
    }),
  };
}

function cannotSatisfyResult(
  action: Extract<AgentNextAction, { type: "cannot_satisfy" }>,
  hypothesis: PlanningHypothesis,
  actions: AgentNextAction[],
  executions: ExecutedToolCall[],
  validations: TripValidation[],
  budget: PlannerBudgetState,
  factBundles: FactBundle[],
): SpecifiedPlanCoordinatorResult {
  const factIds = new Set(action.conflictFactIds);
  const actionIds = new Set(action.suggestedRelaxationIds);
  return {
    status: "cannot_satisfy",
    conflictFactIds: action.conflictFactIds,
    suggestedRelaxationIds: action.suggestedRelaxationIds,
    factBundle: factBundleSchema.parse({
      facts: factBundles.flatMap((bundle) => bundle.facts).filter((fact) => factIds.has(fact.id)),
      allowedComparisonDimensions: [],
      allowedFollowUpActions: factBundles
        .flatMap((bundle) => bundle.allowedFollowUpActions)
        .filter((item) => actionIds.has(item.id)),
    }),
    trace: trace(hypothesis, actions, executions, validations, budget),
  };
}

async function assemble(
  action: ProposePlanAction,
  request: PlannableTripRequest,
  input: SpecifiedPlanCoordinatorInput,
  executions: ExecutedToolCall[],
  factBundles: FactBundle[],
  budget: PlannerBudgetState,
) {
  return assembleProposedPlan({
    tripId: input.tripId,
    action,
    request,
    executedCalls: executions,
    factBundles,
    budget,
    locationGraph: input.locationGraph,
    knownMarketIds: input.knownMarketIds,
    supportedThemes: input.supportedThemes,
    expectedInventoryVersion: input.expectedInventoryVersion,
    resolveOffer: input.resolveOffer,
  });
}

export async function coordinateSpecifiedDestinationPlan(
  input: SpecifiedPlanCoordinatorInput,
): Promise<SpecifiedPlanCoordinatorResult> {
  let request: PlannableTripRequest;
  try {
    request = requirePlannableRequest(input.request);
  } catch {
    throw new PlanCoordinatorError("INVALID_CONTEXT", "Coordinator requires a canonical plannable request");
  }
  if (request.destination.kind !== "specified") {
    throw new PlanCoordinatorError(
      "INVALID_CONTEXT",
      "Specified-destination coordinator cannot run open-ended discovery",
    );
  }

  let budget = initialBudget(input.optionalClarificationUsed ?? false);
  // Route shape and evidence coverage are deterministic in the production
  // model. Keep the interface hook for test doubles and alternate strategies.
  const hypothesis = input.model.deterministicStrategy
    ? await createDeterministicPlannerModel().createPlanningHypothesis({
        request,
        catalogScope: {
          locationGraph: input.locationGraph,
          marketIds: [...input.knownMarketIds],
          supportedThemes: [...input.supportedThemes],
        },
      }) as PlanningHypothesis
    : await modelHypothesis(input.model, request, input);
  const hypothesisValidation = validatePlanningHypothesis(
    hypothesis,
    coordinatorScope(request, input),
    budget,
  );
  if (!hypothesisValidation.valid) {
    throw new PlanCoordinatorError(
      "INVALID_MODEL_OUTPUT",
      "Planner hypothesis failed deterministic scoped validation",
      { phase: "hypothesis", violations: hypothesisValidation.violations },
    );
  }

  const actions: AgentNextAction[] = [];
  const executions: ExecutedToolCall[] = [];
  const validations: TripValidation[] = [];
  const firstBatch = await executeToolPlan(
    hypothesis.toolPlan,
    {
      request,
      knownLocationIds: coordinatorScope(request, input).knownLocationIds,
      knownMarketIds: input.knownMarketIds,
      knownSelectionIds: new Set(),
      supportedThemes: input.supportedThemes,
      budget,
      roundKind: "evidence",
    },
    input.inventoryServices,
  );
  executions.push(...firstBatch.results);
  budget = firstBatch.nextBudget;
  let factBundles = [factsFromExecutions(firstBatch.results)];

  let phase: Exclude<CoordinatorPhase, "hypothesis"> = "after_evidence_round_1";
  let action = await modelAction(input.model, {
    phase,
    request,
    hypothesis,
    observations: executions.map((execution) => execution.observation),
    factBundles,
    budget,
  });
  validateAction(action, request, input, executions, factBundles, budget, phase);
  actions.push(action);

  if (action.type === "clarify") {
    return clarificationResult(action, hypothesis, actions, executions, validations, budget);
  }
  if (action.type === "cannot_satisfy") {
    return cannotSatisfyResult(action, hypothesis, actions, executions, validations, budget, factBundles);
  }
  if (action.type === "present_destination_options") {
    throw new PlanCoordinatorError(
      "WORKFLOW_VIOLATION",
      "Specified-destination planning cannot present destination discovery options",
      { phase },
    );
  }
  if (action.type === "search_more") {
    const secondBatch = await executeToolPlan(
      action.toolPlan,
      {
        request,
        knownLocationIds: coordinatorScope(request, input).knownLocationIds,
        knownMarketIds: input.knownMarketIds,
        knownSelectionIds: new Set(),
        supportedThemes: input.supportedThemes,
        budget,
        roundKind: "evidence",
      },
      input.inventoryServices,
    );
    executions.push(...secondBatch.results);
    budget = secondBatch.nextBudget;
    factBundles = [...factBundles, factsFromExecutions(secondBatch.results)];
    phase = "after_evidence_round_2";
    action = await modelAction(input.model, {
      phase,
      request,
      hypothesis,
      observations: executions.map((execution) => execution.observation),
      factBundles,
      budget,
    });
    validateAction(action, request, input, executions, factBundles, budget, phase);
    actions.push(action);
    if (action.type === "clarify") {
      return clarificationResult(action, hypothesis, actions, executions, validations, budget);
    }
    if (action.type === "cannot_satisfy") {
      return cannotSatisfyResult(action, hypothesis, actions, executions, validations, budget, factBundles);
    }
    if (action.type !== "propose_plan") {
      throw new PlanCoordinatorError(
        "WORKFLOW_VIOLATION",
        "Second evidence round must end in a plan or grounded conflict",
        { phase },
      );
    }
  }

  if (action.type !== "propose_plan") {
    throw new PlanCoordinatorError(
      "WORKFLOW_VIOLATION",
      "Evidence phase did not produce a proposed plan",
      { phase },
    );
  }
  let assembly = await assemble(action, request, input, executions, factBundles, budget);
  validations.push(assembly.projection.validation);
  if (assembly.status === "valid") {
    return {
      status: "completed",
      trip: assembly.trip,
      projection: assembly.projection,
      trace: trace(hypothesis, actions, executions, validations, budget),
    };
  }

  const validationFacts = validationFactBundle(input.tripId, assembly.projection.validation, request);
  factBundles = [...factBundles, validationFacts];
  phase = "repair_after_validation";
  let repairAction = await modelAction(input.model, {
    phase,
    request,
    hypothesis,
    observations: executions.map((execution) => execution.observation),
    factBundles,
    budget,
    validationFeedback: {
      validation: assembly.projection.validation,
      factBundle: validationFacts,
      selectedCandidateIds: assembly.selectedCandidateIds,
    },
  });
  validateAction(repairAction, request, input, executions, factBundles, budget, phase);
  actions.push(repairAction);

  if (repairAction.type === "cannot_satisfy") {
    budget = { ...budget, repairRoundsUsed: 1 };
    return cannotSatisfyResult(
      repairAction,
      hypothesis,
      actions,
      executions,
      validations,
      budget,
      factBundles,
    );
  }
  if (repairAction.type === "search_more") {
    const repairBatch = await executeToolPlan(
      repairAction.toolPlan,
      {
        request,
        knownLocationIds: coordinatorScope(request, input).knownLocationIds,
        knownMarketIds: input.knownMarketIds,
        knownSelectionIds: new Set(),
        supportedThemes: input.supportedThemes,
        budget,
        roundKind: "repair",
      },
      input.inventoryServices,
    );
    executions.push(...repairBatch.results);
    budget = repairBatch.nextBudget;
    factBundles = [...factBundles, factsFromExecutions(repairBatch.results)];
    phase = "repair_after_search";
    repairAction = await modelAction(input.model, {
      phase,
      request,
      hypothesis,
      observations: executions.map((execution) => execution.observation),
      factBundles,
      budget,
      validationFeedback: {
        validation: assembly.projection.validation,
        factBundle: validationFacts,
        selectedCandidateIds: assembly.selectedCandidateIds,
      },
    });
    validateAction(repairAction, request, input, executions, factBundles, budget, phase);
    actions.push(repairAction);
    if (repairAction.type === "cannot_satisfy") {
      return cannotSatisfyResult(
        repairAction,
        hypothesis,
        actions,
        executions,
        validations,
        budget,
        factBundles,
      );
    }
  }

  if (repairAction.type !== "propose_plan") {
    throw new PlanCoordinatorError(
      "WORKFLOW_VIOLATION",
      "Repair phase must end in one revised plan or a grounded conflict",
      { phase },
    );
  }
  if (budget.repairRoundsUsed === 0) {
    budget = { ...budget, repairRoundsUsed: 1 };
  }
  assembly = await assemble(repairAction, request, input, executions, factBundles, budget);
  validations.push(assembly.projection.validation);
  if (assembly.status === "valid") {
    return {
      status: "completed",
      trip: assembly.trip,
      projection: assembly.projection,
      trace: trace(hypothesis, actions, executions, validations, budget),
    };
  }
  return {
    status: "invalid_after_repair",
    trip: assembly.trip,
    projection: assembly.projection,
    factBundle: validationFactBundle(input.tripId, assembly.projection.validation, request),
    trace: trace(hypothesis, actions, executions, validations, budget),
  };
}
